workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  PY_VERSION: "3.10"
  POETRY_VERSION: "1.2.2"
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


image: python:${PY_VERSION}

stages:
  - lint
  - test

#cache:
#  key:
#    files:
#      - poetry.lock
#      - .gitlab-ci.yml
#    prefix: ${CI_JOB_NAME}
#  paths:
#    - .venv
#    - .cache/pip

run_linters:
  stage: lint
  tags:
    - local
    - docker
  before_script:
    - pip install poetry==${POETRY_VERSION}
    - poetry config virtualenvs.in-project true
    - poetry install --only linters
  script:
    - poetry run black --check --diff .
    - poetry run isort --check --diff .

run_unit_tests:
  stage: test
  tags:
    - local
    - docker
  before_script:
    - pip install poetry==${POETRY_VERSION}
    - poetry config virtualenvs.in-project true
    - poetry install --without linters --without dev
  script:
    - poetry run pytest -vv --color=yes
