workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  python_version: "3.10"
  poetry_version: "1.2.2"

image: python:${python_version}

stages:
  - lint
  - test

run_linters:
  stage: lint
  tags:
    - local
    - docker
  before_script:
    - pip install poetry==${poetry_version}
    - poetry config virtualenvs.create false
    - poetry install --only lint
  script:
    - poetry run black --check --diff .
    - poetry run isort --check --diff .