version: "3"

services:
  rabbit:
    build:
      context: docker/rabbitmq/
      dockerfile: Dockerfile
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    volumes:
      - rabbit_data_volume:/var/lib/rabbitmq/
      - rabbit_logs_volume:/var/log/rabbitmq/
    restart: unless-stopped

  pg:
    image: postgres:alpine
    container_name: pg
    expose:
      - 5432
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PSWD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - rabbit
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: ./docker/admin/Dockerfile
    container_name: admin
    environment:
      DJANGO_SUPERUSER_PASSWORD: $SU_PSWD
      DJANGO_SUPERUSER_EMAIL: $SU_EMAIL
    ports:
      - "8000:8000"
    depends_on:
      - pg
      - app
    restart: unless-stopped

  pymailer:
    build:
      context: ../pymailer
      dockerfile: Dockerfile
    container_name: pymailer
    depends_on:
      - rabbit
    restart: unless-stopped
volumes:
  pg_data_volume:
  rabbit_data_volume:
  rabbit_logs_volume: