version: "3"

services:
  rabbit:
    image: ivaaahn/rabbitmq:0.1
    container_name: retailer-rmq
    expose:
      - 5672
      - 15672
    volumes:
      - rabbit_data_volume:/var/lib/rabbitmq/
      - rabbit_logs_volume:/var/log/rabbitmq/
    restart: unless-stopped

  pg:
    image: postgres:alpine
    container_name: pg
#    ports:
#      - "8765:5432"
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PSWD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: ivaaahn/retailer:0.1.10
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - rabbit
    restart: unless-stopped

  pymailer:
    image: ivaaahn/pymailer:0.1
    container_name: pymailer
    depends_on:
      - rabbit
    restart: unless-stopped
volumes:
  pg_data_volume:
  rabbit_data_volume:
  rabbit_logs_volume: