"""orders table was added

Revision ID: 6f1856998bb3
Revises: 9ace568f3e17
Create Date: 2022-05-05 21:18:53.575227

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = "6f1856998bb3"
down_revision = "9ace568f3e17"
branch_labels = None
depends_on = None

vals_rk, name_rk = ("самовывоз", "доставка"), "receive_kind_enum"
vals_s, name_s = (
    "готовится",
    "готов",
    "в пути",
    "доставлен",
    "отменен",
    "завершен",
    "ошибка",
), "order_status_enum"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column(
            "receive_kind",
            ENUM(*vals_rk, name=name_rk),
            server_default="самовывоз",
            nullable=False,
        ),
        sa.Column(
            "status",
            ENUM(*vals_s, name=name_s),
            server_default="готовится",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_orders_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    psql_enum_s = ENUM(*vals_s, name=name_s)
    psql_enum_rk = ENUM(*vals_rk, name=name_rk)

    psql_enum_s.drop(op.get_bind())
    psql_enum_rk.drop(op.get_bind())

    # ### end Alembic commands ###
