"""staff table was added

Revision ID: 547a17f639a0
Revises: 1551d7b903c9
Create Date: 2022-04-17 15:45:15.023886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

revision = "547a17f639a0"
down_revision = "1551d7b903c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_staff_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_staff_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
    )

    permissions = (
        text("grant select on staff to defretailer;"),
        text("grant all on staff to adretailer;"),
    )

    for perm in permissions:
        op.get_bind().execute(perm)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff")

    # ### end Alembic commands ###
