"""customers and addresses tables were added

Revision ID: 39f94d3d830d
Revises: b6a744784764
Create Date: 2022-04-03 01:37:44.035674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39f94d3d830d"
down_revision = "b6a744784764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_addresses",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("entrance", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("flat", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_addresses")),
    )
    op.create_index(
        op.f("ix_customer_addresses_city"), "customer_addresses", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_customer_addresses_street"),
        "customer_addresses",
        ["street"],
        unique=False,
    )
    op.create_table(
        "shop_addresses",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("building", sa.Text(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_addresses")),
    )
    op.create_index(
        op.f("ix_shop_addresses_city"), "shop_addresses", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_shop_addresses_street"), "shop_addresses", ["street"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["customer_addresses.id"],
            name=op.f("fk_customers_address_id_customer_addresses"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["web_users.id"], name=op.f("fk_customers_user_id_web_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    op.drop_index(op.f("ix_shop_addresses_street"), table_name="shop_addresses")
    op.drop_index(op.f("ix_shop_addresses_city"), table_name="shop_addresses")
    op.drop_table("shop_addresses")
    op.drop_index(op.f("ix_customer_addresses_street"), table_name="customer_addresses")
    op.drop_index(op.f("ix_customer_addresses_city"), table_name="customer_addresses")
    op.drop_table("customer_addresses")
    # ### end Alembic commands ###
