"""customers and addresses tables were added

Revision ID: 39f94d3d830d
Revises: 3dc8529d8689
Create Date: 2022-04-03 01:37:44.035674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39f94d3d830d"
down_revision = "3dc8529d8689"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["web_users.id"], name=op.f("fk_customers_user_id_web_users")
        ),
    )
    op.create_table(
        "customer_addresses",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("entrance", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("flat", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_addresses")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_addresses_customer_id_customers"),
        ),
    )
    op.create_index(
        op.f("ix_customer_addresses_city"), "customer_addresses", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_customer_addresses_street"),
        "customer_addresses",
        ["street"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    op.drop_index(op.f("ix_customer_addresses_street"), table_name="customer_addresses")
    op.drop_index(op.f("ix_customer_addresses_city"), table_name="customer_addresses")
    op.drop_table("customer_addresses")
    # ### end Alembic commands ###
