"""customers and addresses tables were added

Revision ID: d458c13646b7
Revises: b6a744784764
Create Date: 2022-04-02 21:20:30.842606

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd458c13646b7'
down_revision = 'b6a744784764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('house', sa.Text(), nullable=False),
    sa.Column('entrance', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('flat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_customers_address_id_addresses')),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], name=op.f('fk_customers_user_id_web_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('addresses')
    # ### end Alembic commands ###
