"""customers and addresses tables was added

Revision ID: 49f94d3d830d
Revises: 59ca10a9bd19
Create Date: 2022-04-03 01:37:44.035674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49f94d3d830d"
down_revision = "59ca10a9bd19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
    )
    op.create_index(op.f("ix_shops_city"), "shops", ["city"], unique=False)
    op.create_index(op.f("ix_shops_street"), "shops", ["street"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shops_street"), table_name="shops")
    op.drop_index(op.f("ix_shops_city"), table_name="shops")
    op.drop_table("shops")
    # ### end Alembic commands ###
