"""shop_addresses table was added

Revision ID: 9b55a88e1cd5
Revises: 547a17f639a0
Create Date: 2022-05-01 14:02:52.627892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b55a88e1cd5"
down_revision = "547a17f639a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops_addresses",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=False),
        sa.Column("house", sa.Text(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops_addresses")),
    )
    op.create_index(
        op.f("ix_shops_addresses_city"), "shops_addresses", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_shops_addresses_street"), "shops_addresses", ["street"], unique=False
    )
    op.add_column("shops", sa.Column("address_id", sa.Integer(), nullable=False))
    op.drop_index("ix_shops_city", table_name="shops")
    op.drop_index("ix_shops_street", table_name="shops")
    op.create_foreign_key(
        op.f("fk_shops_address_id_shops_addresses"),
        "shops",
        "shops_addresses",
        ["address_id"],
        ["id"],
    )
    op.drop_column("shops", "city")
    op.drop_column("shops", "floor")
    op.drop_column("shops", "street")
    op.drop_column("shops", "house")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shops", sa.Column("house", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "shops", sa.Column("street", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "shops", sa.Column("floor", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "shops", sa.Column("city", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(
        op.f("fk_shops_address_id_shops_addresses"), "shops", type_="foreignkey"
    )
    op.create_index("ix_shops_street", "shops", ["street"], unique=False)
    op.create_index("ix_shops_city", "shops", ["city"], unique=False)
    op.drop_column("shops", "address_id")
    op.drop_index(op.f("ix_shops_addresses_street"), table_name="shops_addresses")
    op.drop_index(op.f("ix_shops_addresses_city"), table_name="shops_addresses")
    op.drop_table("shops_addresses")
    # ### end Alembic commands ###
