version: "3"


services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
     - app
     - admin
    ports:
      - "80:80"
      - "443:443"
    environment:
      S3_STORAGE_URL: $S3_STORAGE_URL
      S3_BUCKET_NAME: $S3_BUCKET_NAME
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/data/log:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - net

  app:
    image: ivaaahn/retailer:${RETAILER_VERSION}
    container_name: app
    environment:
      WAIT_HOSTS: redis:6379, rabbit:5672
      WAIT_TIMEOUT: 900
      WAIT_SLEEP_INTERVAL: 5
    user: "${UID_GID}"
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
      - redis
    extra_hosts:
      - "pg:10.128.0.19"
    restart: unless-stopped
    networks:
      - net

  admin:
    image: ivaaahn/retailer-admin:${RETAILER_ADMIN_VERSION}
    container_name: admin
    environment:
      DJANGO_SUPERUSER_PASSWORD: $SU_PSWD
      DJANGO_SUPERUSER_EMAIL: $SU_EMAIL
      WAIT_HOSTS: app:8080, redis:6379
      WAIT_TIMEOUT: 900
      WAIT_SLEEP_INTERVAL: 5
    ports:
      - "8000:8000"
    depends_on:
      - app
      - redis
    extra_hosts:
      - "pg:10.128.0.19"
    restart: unless-stopped
    networks:
      - net

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6379
    volumes:
      - redis_data_volume:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - net

  pymailer:
    image: ivaaahn/pymailer:${PYMAILER_VERSION}
    container_name: pymailer
    depends_on:
      - rabbit
    restart: unless-stopped
    networks:
      - net

  rabbit:
    image: ivaaahn/rabbitmq:${RABBITMQ_VERSION}
    container_name: retailer-rmq
    expose:
      - 5672
      - 15672
    volumes:
      - rabbit_data_volume:/data/lib/rabbitmq/
      - rabbit_logs_volume:/data/log/rabbitmq/
    restart: unless-stopped
    networks:
      - net

volumes:
  redis_data_volume:
  rabbit_data_volume:
  rabbit_logs_volume:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16