version: "3"


services:
  app:
    image: git.iu7.bmstu.ru:5050/retailer/retailer/main:1.0
    container_name: retailer-app
    environment:
      WAIT_HOSTS: redis:6379, rabbit:5672
      WAIT_TIMEOUT: 900
      WAIT_SLEEP_INTERVAL: 5
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
      - redis
    restart: unless-stopped

  pymailer:
    image: git.iu7.bmstu.ru:5050/retailer/aio-pymailer/main:1.0
    container_name: retailer-mailer
    depends_on:
      - rabbit
    restart: unless-stopped

  pg:
    image: postgres:alpine
    container_name: retailer-pg
    expose:
      - 5432
    environment:
      POSTGRES_DB: retailer
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: retailer-redis
    expose:
      - 6379
    restart: unless-stopped

  rabbit:
    image: rabbitmq:3-alpine
    container_name: retailer-rabbitmq
    expose:
      - 5672
    restart: unless-stopped
