# Generated by Django 4.0.4 on 2022-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopsModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("city", models.TextField()),
                ("street", models.TextField()),
                ("house", models.TextField()),
                ("floor", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "db_table": "shops",
                "managed": False,
            },
        ),
    ]
