@startuml "Retailer"

title Варианты использования приложения "Retailer"

left to right direction

actor :Клиент: as Cli
actor :Сотрудник: as Staff
actor :Менеджер: as Admin


rectangle "Функционал клиента" {
    usecase "Просмотреть профиль" as CheckProfile
    usecase "Изменить профиль" as UpdateProfile

    usecase "Просмотреть список торговых точек" as ShopList
    usecase "Выбрать торговую точку для заказа" as ChooseShop
    usecase "Проверить наличие (цену) товаров" as ShopProductsInfo
    usecase "Просмотреть информацию о торговой точке" as ShopInfo

    usecase "Получить список товаров" as CliProductsListInfo
    usecase "Получить информацию о товаре" as ShopProductInfo
    usecase "Добавить товар в корзину" as AddProductToCart

    usecase "Просмотреть корзину" as CheckCart
    usecase "Удалить товар" as RemoveProductFromCart
    usecase "Изменить количество единиц товара" as EditProductInCart
    usecase "Оформить заказ" as ApplyOrder

    usecase "Получить список заказов" as OrdersList
    usecase "Получить информацию о заказе" as OrderInfo
}

rectangle "Функционал сотрудника" {
    usecase "Просмотреть список доступных торговых точек" as StaffShopList
    usecase "Просмотреть информацию о выбранной торговой точке" as StaffShopInfo
    usecase "Просмотреть ассортимент товаров торговой точки" as StaffShopProductsInfo
    usecase "Получить базовый ассортимент товара" as StaffProductListInfo
    usecase "Просмотреть описание товара" as StaffProductInfo
    usecase "Редактировать цену/наличие товара" as StaffProductEdit
}

rectangle "Функционал менеджера" {
    usecase "Получить список всех торговых точек" as AdminShopList
	usecase "Получить список товаров торговой точки" as AdminShopInfo
	usecase "Редактировать цену/наличие товара" as AdminProductEdit
    usecase "Просмотреть список сотрудников торговой точки" as AdminShopStaffList
    usecase "Забрать доступ у сотрудника" as RevokeStaff
    usecase "Дать доступ новому сотруднику" as GrantStaff
    usecase "Получить список пользователей" as AdminStaffList
    usecase "Создать аккаунт сотруднику" as AdminStaffCreate
    usecase "Удалить аккаунт сотрудника" as AdminStaffRemove
    usecase "Получить базовый ассортимент товара" as AdminProductList
    usecase "Редактировать описание" as AdminEditProduct
    usecase "Добавить товар" as AdminAddProduct
    usecase "Удалить товар" as AdminRemoveProduct
    usecase "Просмотреть статистику" as AdminGetStat
    usecase "Получить список заказов" as AdminOrdersList
}


Admin --> AdminShopList
AdminShopList ..> AdminShopStaffList : include
AdminShopStaffList ..> RevokeStaff : include
AdminShopStaffList ..> GrantStaff : include
AdminShopList ..> AdminShopInfo : include
AdminShopInfo ..> AdminProductEdit : include

Admin --> AdminStaffList
AdminStaffList ..> AdminStaffCreate
AdminStaffList ..> AdminStaffRemove

Admin --> AdminProductList
AdminProductList ..> AdminAddProduct : include
AdminProductList ..> AdminEditProduct : include
AdminProductList ..> AdminRemoveProduct : include

Admin --> AdminGetStat
Admin --> AdminOrdersList


Staff --> StaffShopList
StaffShopList ..> StaffShopInfo : include
StaffShopList ..> StaffShopProductsInfo : include

Staff --> StaffProductListInfo
StaffProductListInfo ..> StaffProductInfo : include

StaffShopProductsInfo ..> StaffProductEdit : include


Cli --> ShopList
ShopList ..> ShopInfo : include
ShopList ..> ChooseShop : include
ShopList ..> ShopProductsInfo : include

Cli --> CliProductsListInfo
CliProductsListInfo ..> AddProductToCart : include
CliProductsListInfo ..> ShopProductInfo : include

Cli --> OrdersList
OrdersList ..> OrderInfo : include

Cli --> CheckCart
CheckCart ..> RemoveProductFromCart : include
CheckCart ..> EditProductInCart : include
CheckCart ..> ApplyOrder : include

Cli --> CheckProfile
CheckProfile ..> UpdateProfile : include


@enduml
