@startuml "Retailer"

title Варианты использования приложения "Retailer"

left to right direction

actor :Менеджер: as Admin


rectangle "Функционал менеджера" {
    usecase "Взаимодействие с сотрудниками" as Staff
    usecase "Забрать доступ" as RevokeStaff
    usecase "Дать доступ" as GrantStaff
    usecase "Получить список" as AdminStaffList
    usecase "Создать аккаунт" as AdminStaffCreate
    usecase "Удалить аккаунт" as AdminStaffRemove

    usecase "Взаимодействие с торговыми точками" as Shop
    usecase "Получить список всех торговых точек" as AdminShopList
	usecase "Получить список товаров торговой точки" as AdminShopInfo
    usecase "Просмотреть статистику" as AdminGetStat
}


Admin --> Staff
Staff ..> RevokeStaff
Staff ..> GrantStaff
Staff ..> AdminStaffList
Staff ..> AdminStaffCreate
Staff ..> AdminStaffRemove

Admin --> Shop
Shop ..> AdminShopList
Shop ..> AdminShopInfo
Shop ..> AdminGetStat

@enduml
