@startuml "Retailer"

title Варианты использования приложения "Retailer"

left to right direction

actor :Клиент: as Cli

rectangle "Функционал клиента" {
    usecase "Взаимодействие с профилем" as Profile
    usecase "Просмотреть профиль" as CheckProfile
    usecase "Изменить профиль" as UpdateProfile


    usecase "Взаимодействие с торговыми точками" as Shops
    usecase "Просмотреть список торговых точек" as ShopList
    usecase "Выбрать торговую точку для заказа" as ChooseShop
    usecase "Просмотреть информацию о торговой точке" as ShopInfo


    usecase "Взаимодействие с товарами" as Products
    usecase "Проверить наличие (цену) товаров" as ShopProductsInfo
    usecase "Получить список товаров" as CliProductsListInfo
    usecase "Получить информацию о товаре" as ShopProductInfo
    usecase "Добавить товар в корзину" as AddProductToCart
}


Cli --> Profile
Profile ..> CheckProfile
Profile ..> UpdateProfile

Cli --> Products
Products ..> ShopProductsInfo
Products ..> CliProductsListInfo
Products ..> ShopProductInfo
Products ..> AddProductToCart

Cli --> Shops
Shops ..> ShopList
Shops ..> ShopInfo
Shops ..> ChooseShop

@enduml
