# Generated by Django 4.0.4 on 2022-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("name", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("photo", models.TextField(null=True)),
                ("birthday", models.DateField(null=True)),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("regular", "Без привилегий"),
                            ("staff", "Штатный сотрудник"),
                            ("superuser", "Администратор"),
                        ],
                        default="regular",
                    ),
                ),
            ],
        ),
    ]
