# Generated by Django 4.0.4 on 2022-05-01 20:49
from django.contrib.auth import get_user_model
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def create_groups(apps, schema_migration):
    emit_post_migrate_signal(2, False, "default")

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    view_product = Permission.objects.get(codename="view_productmodel")
    view_shop = Permission.objects.get(codename="view_shopmodel")
    view_product_category = Permission.objects.get(codename="view_productcategorymodel")

    view_shop_product = Permission.objects.get(codename="view_shopproductmodel")
    add_shop_product = Permission.objects.get(codename="add_shopproductmodel")
    change_shop_product = Permission.objects.get(codename="change_shopproductmodel")
    delete_shop_product = Permission.objects.get(codename="delete_shopproductmodel")

    staff_permissions = [
        view_shop,
        view_product,
        view_product_category,
        view_shop_product,
        add_shop_product,
        change_shop_product,
        delete_shop_product,
    ]

    staff = Group(name="staff")
    staff.save()

    staff.permissions.set(staff_permissions)


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["staff"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, revert_migration),
    ]
