name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
#        - name: Check out the repo
#        - uses: actions/checkout@v3
#
#        - name: Login to DockerHub
#          uses: docker/login-action@v1
#          with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#        - name: Build the Retailer App
#          uses: docker/build-push-action@v2
#          with:
#            file: ./deploy/api/Dockerfile
#            context: .
#            push: true
#            tags: ${{ secrets.DOCKERHUB_USERNAME }}/retailer:$(git rev-parse --short "$GITHUB_SHA")
#
#        - name: Build the Retailer Admin
#          uses: docker/build-push-action@v2
#          with:
#            file: ./deploy/admin/Dockerfile
#            context: .
#            push: true
#            tags: ${{ secrets.DOCKERHUB_USERNAME }}/retailer-admin:$(git rev-parse --short "$GITHUB_SHA")

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DOCKER_SSH_HOST}
            username: ${{ secrets.DOCKER_SSH_USER }}
            key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            port: ${{ secrets.PORT }}
            script: whoami
